import { useEffect, useMemo, useState } from "react";
import { Background, Controls, MarkerType, MiniMap, Position, ReactFlow, type Edge, type Node } from "@xyflow/react";
import { AlertTriangle, GitBranch, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { loadRepositories, loadSnapshot, type CommitRecord, type Snapshot } from "./api";
import { buildPullRequestGraph, rankBottlenecks, type PullRequestModel } from "./graphModel";

const STATUS_ORDER = ["READY", "BLOCKED", "WAITING", "NEEDS_REVIEW", "STALE"] as const;
const label = (status: PullRequestModel["status"]) => status === "NEEDS_REVIEW" ? "NEEDS REVIEW" : status;

function prGraph(pulls: PullRequestModel[], selected: number | null) {
  const levels = new Map<number, number>(); const byNumber = new Map(pulls.map((pull) => [pull.number, pull]));
  const levelOf = (pull: PullRequestModel): number => { if (levels.has(pull.number)) return levels.get(pull.number)!; const upstream = pull.dependencies[0] ? byNumber.get(pull.dependencies[0]) : undefined; const level = upstream ? levelOf(upstream) + 1 : 0; levels.set(pull.number, level); return level; };
  const lanes = new Map<number, number>();
  const nodes: Node[] = pulls.map((pull) => { const level = levelOf(pull); const lane = lanes.get(level) ?? 0; lanes.set(level, lane + 1); return { id: `pr-${pull.number}`, position: { x: level * 330, y: lane * 184 }, sourcePosition: Position.Right, targetPosition: Position.Left, className: `pr-node pr-${pull.status.toLowerCase().replace("_","-")} ${selected === pull.number ? "selected" : ""}`, style: { width: 286 }, data: { label: <div className="pr-content"><div className="pr-top"><strong>#{pull.number}</strong><span className={`status s-${pull.status.toLowerCase().replace("_","-")}`}>{label(pull.status)}</span></div><div className="pr-title">{pull.title}</div><div className="pr-meta">{pull.author} · {pull.head} → {pull.base}</div><div className="pr-bottom"><span>CI {pull.checks.some((c)=>c.status!=="completed") ? "…" : pull.checks.some((c)=>c.conclusion==="failure") ? "✕" : "✓"}</span><span>Review {pull.approvalCount ? "✓" : "—"}</span><span>blocks {pull.downstreamCount}</span></div></div> } }; });
  const edges: Edge[] = pulls.flatMap((pull) => pull.dependencies.map((dependency) => ({ id: `edge-${dependency}-${pull.number}`, source: `pr-${dependency}`, target: `pr-${pull.number}`, markerEnd: { type: MarkerType.ArrowClosed }, animated: selected === pull.number || selected === dependency })));
  return { nodes, edges };
}

function CommitGraph({ commits }: { commits: CommitRecord[] }) {
  const branches = [...new Set(commits.map((commit) => commit.branch))];
  const nodes: Node[] = commits.slice(0, 80).map((commit, index) => ({ id: commit.sha, position: { x: index * 155, y: Math.max(0, branches.indexOf(commit.branch)) * 105 }, sourcePosition: Position.Right, targetPosition: Position.Left, className: "commit-node", style: { width: 140 }, data: { label: <div className="commit-content"><strong>{commit.sha.slice(0,7)}</strong><span>{commit.message}</span><small>{commit.prNumber ? `PR #${commit.prNumber}` : commit.branch}</small></div> } }));
  const ids = new Set(nodes.map((node) => node.id)); const edges: Edge[] = commits.slice(0,80).flatMap((commit) => commit.parents.filter((parent)=>ids.has(parent)).map((parent)=>({id:`${parent}-${commit.sha}`,source:parent,target:commit.sha})));
  return <div className="graph commit-graph" data-testid="commit-graph"><ReactFlow nodes={nodes} edges={edges} fitView minZoom={0.12}><Background /><Controls /></ReactFlow></div>;
}

function nextAction(pull: PullRequestModel) { if (pull.status === "READY") return "Merge decision needed"; if (pull.status === "BLOCKED") return pull.blockers[0] ?? "Resolve blocker"; if (pull.status === "WAITING") return `Resolve upstream #${pull.dependencies[0]}`; if (pull.status === "STALE") return "Revalidate or close stale work"; return "Human review needed"; }

export function App() {
  const [repos, setRepos] = useState<string[]>([]); const [repo, setRepo] = useState(""); const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<number | null>(null); const [tab, setTab] = useState<"flow"|"commits">("flow"); const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState("ALL");
  useEffect(() => { loadRepositories().then((items)=>{ setRepos(items); setRepo((current)=>current || items[0] || ""); }).catch((reason)=>{ setError(reason.message); setLoading(false); }); }, []);
  async function refresh(target: string, force = false) { if (!target) return; setLoading(true); setError(null); if (snapshot?.repository !== target) setSnapshot(null); try { setSnapshot(await loadSnapshot(target, force)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Failed to load GitHub data"); } finally { setLoading(false); } }
  useEffect(() => { if (repo) void refresh(repo); }, [repo]);
  const pulls = useMemo(()=>snapshot ? buildPullRequestGraph(snapshot.pulls) : [],[snapshot]); const filtered = useMemo(()=>pulls.filter((pull)=>{ const match = !query || `${pull.number} ${pull.title} ${pull.author} ${pull.head} ${pull.base}`.toLowerCase().includes(query.toLowerCase()); return match && (statusFilter === "ALL" || pull.status === statusFilter); }),[pulls,query,statusFilter]); const ranked = useMemo(()=>rankBottlenecks(pulls).slice(0,5),[pulls]); const selectedPull = pulls.find((pull)=>pull.number===selected) ?? null; const graph = useMemo(()=>prGraph(filtered,selected),[filtered,selected]);
  const counts = Object.fromEntries(STATUS_ORDER.map((status)=>[status,pulls.filter((pull)=>pull.status===status).length]));
  return <main className="shell" data-testid="dashboard-root">
    <header className="header"><div><div className="eyebrow"><GitBranch size={15}/> DEVELOPMENT FLOW</div><h1>PR Flow Dashboard</h1><p>Resolve the work that unlocks the most downstream changes.</p></div><div className="header-actions"><label>Repository<select aria-label="Repository" value={repo} onChange={(event)=>{setSelected(null);setRepo(event.target.value);}}>{repos.map((item)=><option key={item}>{item}</option>)}</select></label><button onClick={()=>void refresh(repo,true)} disabled={loading}><RefreshCw size={16}/> Refresh</button></div></header>
    <section className="runtime"><span><ShieldCheck size={14}/> server-side GitHub {snapshot?.authentication ?? "…"}</span><span>{snapshot ? `cache ${snapshot.cache.hit ? "hit" : "miss"} · TTL ${snapshot.cache.ttlSeconds}s` : "cache …"}</span><span>{snapshot ? `rate ${snapshot.rateLimit.remaining ?? "?"}/${snapshot.rateLimit.limit ?? "?"}` : "rate …"}</span><span>{snapshot ? `updated ${new Date(snapshot.fetchedAt).toLocaleTimeString()}` : "loading"}</span></section>
    <section className="summary"><div><span>Open PRs</span><strong>{pulls.length}</strong></div>{STATUS_ORDER.map((status)=><div key={status}><span>{label(status)}</span><strong>{counts[status] ?? 0}</strong></div>)}</section>
    {error && <div className="error" role="alert"><AlertTriangle size={18}/><div><strong>GitHub data unavailable</strong><p>{error}</p></div></div>}{loading && !snapshot && <div className="loading">Reading current Pull Requests, reviews, checks and commits…</div>}
    <div className="tabs"><button className={tab==="flow"?"active":""} onClick={()=>setTab("flow")}>PR Flow</button><button className={tab==="commits"?"active":""} onClick={()=>setTab("commits")}>Commit Graph</button></div>
    {snapshot && tab === "flow" && <div className="layout"><section className="panel"><div className="toolbar"><label><Search size={16}/><input aria-label="Search PRs" placeholder="Search PR, title, branch, author" value={query} onChange={(event)=>setQuery(event.target.value)}/></label><select aria-label="Status filter" value={statusFilter} onChange={(event)=>setStatusFilter(event.target.value)}><option value="ALL">All status</option>{STATUS_ORDER.map((status)=><option key={status} value={status}>{label(status)}</option>)}</select></div>{filtered.length ? <div className="graph" data-testid="pr-flow-graph" data-edge-count={graph.edges.length}><ReactFlow nodes={graph.nodes} edges={graph.edges} fitView minZoom={0.3} onNodeClick={(_,node)=>setSelected(Number(node.id.replace("pr-","")))}><Background/><MiniMap pannable zoomable/><Controls/></ReactFlow></div> : <div className="empty">No Pull Requests match this filter.</div>}</section><aside className="attention"><h2>Attention Required</h2><p>Downstream impact first, then blocker severity.</p>{ranked.map((pull,index)=><button key={pull.number} onClick={()=>setSelected(pull.number)}><span className="rank">{index+1}</span><div><strong>#{pull.number} · {label(pull.status)}</strong><span>{pull.title}</span><small>blocks {pull.downstreamCount} · score {pull.bottleneckScore}</small><em>→ {nextAction(pull)}</em></div></button>)}</aside></div>}
    {snapshot && tab === "commits" && <section className="panel"><div className="section-heading"><h2>Commit Graph</h2><p>Recent main and open-PR branch commits, capped at 100 records.</p></div><CommitGraph commits={snapshot.commits}/></section>}
    {selectedPull && <div className="backdrop" onClick={()=>setSelected(null)}><aside className="drawer" role="dialog" aria-label={`PR #${selectedPull.number} details`} onClick={(event)=>event.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className={`status s-${selectedPull.status.toLowerCase().replace("_","-")}`}>{label(selectedPull.status)}{selectedPull.stale ? ` · ${selectedPull.staleDays}d stale` : ""}</span><h2>#{selectedPull.number} {selectedPull.title}</h2><a href={selectedPull.url} target="_blank" rel="noreferrer">Open on GitHub ↗</a><dl><dt>Author</dt><dd>{selectedPull.author}</dd><dt>Branch</dt><dd>{selectedPull.head} → {selectedPull.base}</dd><dt>Head SHA</dt><dd><code>{selectedPull.headSha.slice(0,12)}</code></dd><dt>Commits</dt><dd>{selectedPull.commitCount ?? 0}</dd><dt>Reviewers</dt><dd>{selectedPull.requestedReviewers?.join(", ") || "—"}</dd><dt>Labels</dt><dd>{selectedPull.labels?.join(", ") || "—"}</dd><dt>Depends on</dt><dd>{selectedPull.dependencies.length ? selectedPull.dependencies.map((n)=>`#${n}`).join(", ") : "—"}</dd><dt>Downstream</dt><dd>{selectedPull.downstream.length ? selectedPull.downstream.map((n)=>`#${n}`).join(", ") : "—"}</dd></dl><h3>Why blocked</h3>{selectedPull.blockers.length?<ul>{selectedPull.blockers.map((item)=><li key={item}>{item}</li>)}</ul>:<p>No hard blocker detected.</p>}{selectedPull.changesRequested[0]?.body && <div className="review-note"><strong>Latest change request</strong><p>{selectedPull.changesRequested[0].body.slice(0,500)}</p></div>}<h3>Checks</h3><ul className="check-list">{selectedPull.checks.length ? selectedPull.checks.map((check)=><li key={`${check.name}-${check.url}`}><span>{check.name}</span><strong>{check.status === "completed" ? check.conclusion ?? "completed" : check.status}</strong></li>) : <li>No check-runs reported.</li>}</ul></aside></div>}
  </main>;
}

